### ISSUE TITLE
clock.png in wrong location?

### ISSUE THREAD

**Issue by maxandersen** [ggleblanc2/qlocktwo#1]
both when running the released jar or cloning source and running you get this error:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: input == null!
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1400)
        at com.ggl.qlocktwo.view.QlocktwoFrame.getFrameImage(QlocktwoFrame.java:65)
        at com.ggl.qlocktwo.view.QlocktwoFrame.createPartControl(QlocktwoFrame.java:34)
        at com.ggl.qlocktwo.view.QlocktwoFrame.<init>(QlocktwoFrame.java:28)
        at com.ggl.qlocktwo.Qlocktwo.run(Qlocktwo.java:18)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
```

due to /clock.png not being available.

**Comment by ggleblanc2** [comment]
Hi Max,

Thank you for pointing out this issue.  I have rebuilt the runnable JAR
file and the issue has been resolved.

Gilbert

**Comment by ggleblanc2** [comment]
The clock.png file is in the images folder.  I rebuilt the runnable JAR.
